name: awesome-swift
favicon: null
layout_spectrum: 0.4611513623967767
typography_spectrum: 0.7917201819363981
title: Curated Swift Resources
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.18299598549492657
  lightness: 0.8763889407273382
  saturation: 0.29898975952528417
  rhythmicContrast: 0.5189240169711411
purpose: []
